{
 "title": "mosdns DNS 监控",
 "tags": [ "dns" ],
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "📊 概览", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "🏷️ 查询总数",
   "type": "stat",
   "gridPos": { "x": 0, "y": 7, "w": 2, "h": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "delta(mosdns_metrics_collector_query_total{job=\"mosdns\"}[$__range])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "❌ 错误率",
   "type": "gauge",
   "gridPos": { "x": 2, "y": 7, "w": 2, "h": 3 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(mosdns_metrics_collector_err_total{job=\"mosdns\"}[$__range])/increase(mosdns_metrics_collector_query_total{job=\"mosdns\"}[$__range])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "📋 处理器统计",
   "type": "table",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 1 },
   "targets": [
    {
     "expr": "{app=\"mosdns\"}"
    }
   ]
  },
  {
   "title": "📊 延迟分布",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "ceil(increase(mosdns_metrics_collector_response_latency_millisecond_bucket{le!=\"+Inf\"}[$__interval]))",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "⏱️ 平均延迟",
   "type": "stat",
   "gridPos": { "x": 4, "y": 1, "w": 2, "h": 3 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "delta(mosdns_metrics_collector_response_latency_millisecond_sum{job=\"mosdns\"}[$__range])/delta(mosdns_metrics_collector_response_latency_millisecond_count{job=\"mosdns\"}[$__range])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "⚠️ 错误计数",
   "type": "stat",
   "gridPos": { "x": 4, "y": 7, "w": 2, "h": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(mosdns_metrics_collector_err_total{job=\"mosdns\"}[$__range])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "🚫 广告及黑名单",
   "type": "table",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "{app=\"mosdns\"}"
    }
   ]
  },
  {
   "title": "🏠 本地域名查询",
   "type": "table",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 10 },
   "targets": [
    {
     "expr": "{app=\"mosdns\"}"
    }
   ]
  },
  {
   "title": "🌐 远程主查询-Google",
   "type": "table",
   "gridPos": { "h": 8, "w": 4, "x": 8, "y": 10 },
   "targets": [
    {
     "expr": "{app=\"mosdns\"}"
    }
   ]
  },
  {
   "title": "🔄 远程副查询-Cloudflare",
   "type": "table",
   "gridPos": { "h": 8, "w": 4, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "{app=\"mosdns\"}"
    }
   ]
  },
  {
   "title": "🎬 流媒体查询",
   "type": "table",
   "gridPos": { "h": 8, "w": 4, "x": 16, "y": 10 },
   "targets": [
    {
     "expr": "{app=\"mosdns\"}"
    }
   ]
  },
  {
   "title": "⚡ 错误查询",
   "type": "table",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 10 },
   "targets": [
    {
     "expr": "{app=\"mosdns\"}"
    }
   ]
  },
  { "title": "📝 详细日志", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "📜 实时日志",
   "type": "table",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "{app=\"mosdns\"}"
    }
   ]
  },
  { "title": "📋 查询分类", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "💾 缓存命中率",
   "type": "gauge",
   "gridPos": { "x": 2, "y": 4, "w": 2, "h": 3 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(rate(mosdns_cache_hit_total{tag=\"lazy_cache\"}[$__range])) + sum(rate(mosdns_cache_lazy_hit_total{tag=\"lazy_cache\"}[$__range]))) / sum(rate(mosdns_cache_query_total{tag=\"lazy_cache\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "📦 缓存条目",
   "type": "stat",
   "gridPos": { "x": 0, "y": 4, "w": 2, "h": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mosdns_cache_size_current{tag=\"lazy_cache\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "⏳ 过期命中",
   "type": "stat",
   "gridPos": { "x": 4, "y": 4, "w": 2, "h": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "delta(mosdns_cache_lazy_hit_total{tag=\"lazy_cache\"}[$__range])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "🧠 内存占用",
   "type": "stat",
   "gridPos": { "x": 2, "y": 1, "w": 2, "h": 3 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{job=\"mosdns\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "🔄 CPU 耗时",
   "type": "stat",
   "gridPos": { "x": 0, "y": 1, "w": 2, "h": 3 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "delta(process_cpu_seconds_total{job=\"mosdns\"}[$__range])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}